sj/config/routes.rb
Rails.application.routes.draw do

  get 'white_list/index'

  get 'white_list/new'

  get 'sj/index'

  get 'sj/new'

  get 'index/new'

  resources :users

  resources :sessions, :only=>[:new,:create,:destroy]

  get 'editpwd' => "users#edit_password"
  post 'editpwd' => "users#update_password"
  get 'resetpwd' => "users#reset_password"

  resources :users, :only => [:edit, :update]

  root 'sj#index'

end

sj/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_confirmation_of :password
end

sj/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :user_authenticate

  def current_user
    session[:user_id] ?   User.find(session[:user_id]) : nil
  end

  private
  def user_authenticate
    unless session[:user_id]
      redirect_to new_session_path, :alert=>"请先登录！"
    end
  end

end

sj/app/controllers/base_controller.rb
class BaseController < ApplicationController
  layout "base"


  def current_user
    session[:user_id] ? User.find(session[:user_id]) : nil
  end

  private
  def user_authenticate
    unless session[:user_id]
      redirect_to new_session_path, :alert=>"请先登录！"
    end
  end
end

sj/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :user_authenticate

  def new
   render layout: nil
  end

  def create
    user = User.find_by(name:params[:name]).try(:authenticate,params[:password])
      if user
        if user.status == true
          session[:user_id] = user.id
          flash[:notice] = '登录成功'
          redirect_to root_path
        else
          flash[:alert] = '账户已停用!'
          redirect_to new_session_path
        end
      else
        flash[:alert] = '请检查账户名和密码!'
        redirect_to new_session_path
      end
  end
  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, :alert => "退出成功"
  end

  private
  def user_params
    params.require(:session).permit(:name, :password)
  end

end

sj/app/controllers/sj_controller.rb
class SjController < ApplicationController
  def index
  end

  def new
  end
end

sj/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :permission, :except => [:edit_password,:update_password]

  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user
      flash[:notice]= '添加成功!'
      redirect_to users_path
    else
      flash[:alert]= '添加失败!'
      render :new
    end
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = '修改成功!'

      redirect_to users_path
    else
      flash[:alert] = '修改失败！'
    end
  end

  def edit_password
    @user = User.find(session[:user_id])
  end

  def update_password
    user = User.find_by(name:current_user.name).try(:authenticate,params[:oldpassword])
    if user
      if user.update_attributes(:password=>params[:password])
        flash[:notice] = "修改成功，牢记新密码，请重新登录"
        render 'sj/index'
        session[:user_id] = nil
      else
        flash[:alert] = "修改失败，请联系管理员"

        redirect_to editpwd_path

      end
    else
      flash[:alert] = "原密码输入错误，忘记密码请联系管理员"
      redirect_to editpwd_path

    end
  end
  def reset_password
    @user = User.find(params[:id])
    @user.update(:password=>"123456")
    flash[:notice] = "密码重置成功"
    redirect_to users_path
  end

  def destroy

  end

  private
  def user_params
    params.require(:user).permit(:name,:password, :usertype, :status, :datatype, :website, :description)
  end

  def permission
    if current_user.usertype != 1
      redirect_to root_path, :alert=>"没有权限"
    end
  end


end

sj/app/controllers/white_list_controller.rb
class WhiteListController < ApplicationController
  def index
  end

  def new
  end
end

sj/app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    session[:user_id] ? User.find(session[:user_id]) : nil
  end
end

sj/app/helpers/base_helper.rb
module BaseHelper
end

sj/app/helpers/sessions_helper.rb
module SessionsHelper
end

sj/app/helpers/sj_helper.rb
module SjHelper
end

sj/app/helpers/users_helper.rb
module UsersHelper
end

sj/app/helpers/white_list_helper.rb
module WhiteListHelper

end

sj/app/views/layouts/_flash.html.erb
<%if flash[:notice]%>
    <div class="alert alert-success alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%=flash[:notice]%>
    </div>
<%end%>
<%if flash[:alert]%>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%=flash[:alert]%>
    </div>

<%end%>

sj/app/views/layouts/_navbar.html.erb
<ul class="nav nav-pills navbar-right" style="padding-right: 20px">
  <li role="presentation" >
    <a href="<%= root_path %>" class="dropdown-toggle">
      <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
      首页
    </a>
  </li>

  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      <span class="glyphicon glyphicon-list" aria-hidden="true"></span> 用户管理 <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">

      <li>
        <% if current_user.datatype == 0||current_user.datatype == 2 %>
          精准数据
        <% end %>
      </li>
      <li>
        <% if current_user.datatype == 1||current_user.datatype == 2 %>
            大数据
        <% end %>
      </li>
      <li>
        <% if current_user.usertype == 1 %>
          <%= link_to '账户管理', users_path %>
        <% end %>
      </li>
      <li>
        添加数据
      </li>
      <li>
        白名单
      </li>

    </ul>
  </li>





      <li><%= link_to '修改密码', editpwd_path,:class=>"glyphicon glyphicon-edit" %></li>
      <li><%= link_to '退出登录', session_path(current_user.id),:class=>"glyphicon glyphicon-off", :method => :delete %></li>





</ul>

sj/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sj</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--<link rel="stylesheet" href="/layui/css/layui.css">-->
  <!--<script src="/layui/layui.js"></script>-->
  <%= csrf_meta_tags %>
</head>
<body class="<%="#{controller_name}-#{action_name}"%>" id="<%="#{controller_name}-#{action_name}"%>" data-controller="<%=controller_name.humanize%>" data-action="<%=action_name.humanize%>">

<div class="container">

  <%= render 'layouts/navbar' %>

</div>
<div class="container">


  <%= render 'layouts/flash' %>
  <%= yield %>
</div>
</body>
</html>

sj/app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sj</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--<link rel="stylesheet" href="/layui/css/layui.css">-->
  <!--<script src="/layui/layui.js"></script>-->
  <%= csrf_meta_tags %>
</head>
<body class="<%="#{controller_name}-#{action_name}"%>" id="<%="#{controller_name}-#{action_name}"%>" data-controller="<%=controller_name.humanize%>" data-action="<%=action_name.humanize%>">

<div class="container">

  <%= render 'layouts/navbar' %>

</div>
<div class="container">


  <%= render 'layouts/flash' %>
  <%= yield %>
</div>
</body>
</html>

sj/app/views/sj/index.html.erb
<h1>Sj#index</h1>
<p>Find me in app/views/sj/index.html.erb</p>

sj/app/views/sj/new.html.erb
<h1>Sj#new</h1>
<p>Find me in app/views/sj/new.html.erb</p>

sj/app/views/users/edit.html.erb
<div class="col-lg-12">
  <h3 class="page-header">修改账户
    <%= link_to "返回列表", users_path, :class => "btn btn-default"%>
  </h3>
</div>
<div class="col-lg-12">
<!--<form name="" class="" action="" method="post">-->
<%= form_for @user do |suer| %>
    <!--<input type="hidden" name="user[password]" value="123456">-->
    <div class="form-group">
      <label for="">用户名</label>
      <p class="lead"><%= @user.name %></p>
    </div>
    <div class="form-group">
      <label>
        用户类型
      </label>
      <label class="radio-inline">
        <input type="radio" name="user[usertype]" <%= if @user.usertype==0 then checked="checked" end %> id="" value="0"> 普通
      </label>
      <label class="radio-inline">
        <input type="radio" name="user[usertype]" <%= if @user.usertype==1 then checked="checked" end %> value="1"> 管理员
      </label>
    </div>
    <div class="form-group">
      <label>
        用户状态
      </label>
      <label class="radio-inline">
        <input type="radio" name="user[status]" <%= if @user.status==false then checked="checked" end %> value="false"> 禁用
      </label>
      <label class="radio-inline">
        <input type="radio" name="user[status]" <%= if @user.status==true then checked="checked" end %> value="true"> 启用
      </label>
    </div>
    <div class="form-group">
      <label>
        数据类型
      </label>
      <label class="radio-inline">
        <input type="radio" name="user[datatype]" <%= if @user.datatype==0 then checked="checked" end %> value="0"> 普通版
      </label>
      <label class="radio-inline">
        <input type="radio" name="user[datatype]" <%= if @user.datatype==1 then checked="checked" end %> value="1"> 高级版
      </label>
      <label class="radio-inline">
        <input type="radio" name="user[datatype]" <%= if @user.datatype==2 then checked="checked" end %> value="2"> vip版
      </label>
    </div>
    <div class="form-group">
      <label for="">网站地址</label>
      <input type="text" class="form-control" id="" name="user[website]" value="<%= @user.website %>">
    </div>
    <div class="form-group">
      <label for="">备注信息</label>
      <input type="text" class="form-control" id="" name="user[description]" value="<%= @user.description %>">
    </div>

    <button type="submit" id="submit1" class="btn btn-primary">确认</button>&nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to '取消', users_path  , :class => "btn btn-default" %>


    <!--</form>-->

<% end %>
</div>
<script>
    document.querySelector('#submit1').onclick=function(){
        if (confirm('确认修改?')){
            return true
        }else {
            return false
        }

    }
</script>

sj/app/views/users/edit_password.html.erb
<div class="col-lg-12">
  <h3 class="page-header">修改密码
    <%= link_to "返回首页", root_path, :class => "btn btn-default"%>
  </h3>
</div>
<div class="col-lg-12">

  <%= form_tag(controller: "users", action: "update_password", method: "post") do %>

      <div class="form-group">
        <label for="">原密码</label>
        <%= password_field_tag :oldpassword, params[:oldpassword],:class=>"form-control" %>
      </div>
      <div class="form-group">
        <label for="">新密码</label>
        <%= password_field_tag :password, params[:password],:class=>"form-control" %>
      </div>
      <div class="form-group">
        <label for="">确认密码</label>
        <%= password_field_tag :password_confirmation, params[:password_confirmation],:class=>"form-control" %>
      </div>

      <button type="submit" id="submit1" class="btn btn-primary">确认</button>
      <%= link_to '取消', root_path  , :class => "btn btn-default" %>




  <% end %>
</div>
<script>
    document.querySelector('#submit1').onclick=function(){
        if (confirm('确认修改?')){
            return true
        }else {
            return false
        }

    }
</script>

sj/app/views/users/index.html.erb
<div class="col-lg-12">
  <h3 class="page-header">账户管理
    <%= link_to "添加账户", new_user_path, :class => "btn btn-default" %>

  </h3>
</div>


<div class="col-lg-12">
  <table class="table table-hover">
    <thead>
    <tr>
      <th></th>
      <th>编号</th>
      <th>用户名</th>

      <th>用户类型</th>
      <th>用户状态</th>
      <th>数据类型</th>
      <th>网站域名</th>
      <th>备注信息</th>
      <th>创建时间</th>
      <th>修改</th>


    </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><input type="checkbox"></td>
          <td><%= user.id %></td>
          <td><%= user.name %></td>


          <td><%if user.usertype==0 %>
                <p class="text-success">普通</p>
            <% else %>
               <p class="text-danger">管理员</p>
            <% end %>
          </td>
          <td><% if user.status %>
               <p class="text-success">启用</p>
            <% else %>
                <p class="text-danger">禁用</p>
            <% end %>
          </td>
          <td><%if user.datatype==0 %>
                <p class="text-success">普通版</p>
            <% elsif user.datatype==1 %>
                <p class="text-primary">高级版</p>
            <% else %>
                <p class="text-danger">vip版</p>
            <% end %>
                </td>
          <td><%= user.website %></td>
          <td><%= user.description %></td>
          <td><%= user.created_at %></td>
          <td><%= link_to "修改",edit_user_path(user), :class => "btn btn-primary" %></td>
          <td><%= link_to "重置密码", {:controller => "users", :action => "reset_password" ,:id=>user.id},:data=>{:confirm => "确定要重置密码吗?"}, :class=>"btn btn-danger"%></td>

        </tr>
    <% end %>
    </tbody>
  </table>
  <div class="page">
    共<%= User.all.count %>条数据
    <%= paginate @users %>
  </div>
</div>

sj/app/views/users/new.html.erb
<div class="col-lg-12">
  <h3 class="page-header">添加账户
    <%= link_to "返回列表", users_path, :class => "btn btn-default"%>
  </h3>
</div>
<div class="col-lg-12">
<!--<form name="" class="" action="" method="post">-->
<%= form_for @user do |f| %>
    <input type="hidden" name="user[password]" value="123456">
  <div class="form-group">
    <label for="">用户名</label>
    <input type="text" class="form-control" id="" name="user[name]" placeholder="请输入用户名">
  </div>
  <div class="form-group">
    <label>
      用户类型
    </label>
    <label class="radio-inline">
      <input type="radio" name="user[usertype]" id="" value="0"> 普通
    </label>
    <label class="radio-inline">
      <input type="radio" name="user[usertype]" id="" value="1"> 管理员
    </label>
  </div>
  <div class="form-group">
    <label>
      用户状态
    </label>
    <label class="radio-inline">
      <input type="radio" name="user[status]" id="" value="false"> 禁用
    </label>
    <label class="radio-inline">
      <input type="radio" name="user[status]" id="" value="true"> 启用
    </label>
  </div>
  <div class="form-group">
    <label>
      数据类型
    </label>
    <label class="radio-inline">
      <input type="radio" name="user[datatype]" id="" value="0"> 普通版
    </label>
    <label class="radio-inline">
      <input type="radio" name="user[datatype]" id="" value="1"> 高级版
    </label>
    <label class="radio-inline">
      <input type="radio" name="user[datatype]" id="" value="2"> vip版
    </label>
  </div>
  <div class="form-group">
    <label for="">网站地址</label>
    <input type="text" class="form-control" id="" name="user[website]" placeholder="">
  </div>
  <div class="form-group">
    <label for="">备注信息</label>
    <input type="text" class="form-control" id="" name="user[description]" placeholder="">
  </div>

  <button type="submit" id="submit1" class="btn btn-primary">确认</button>&nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to '取消', users_path  , :class => "btn btn-default" %>


<!--</form>-->

<% end %>
</div>
<script>
  document.querySelector('#submit1').onclick=function(){
      if (confirm('确认添加?')){
          return true
      }else {
          return false
      }

  }
</script>

sj/app/views/white_list/index.html.erb
<h1>WhiteList#index</h1>
<p>Find me in app/views/white_list/index.html.erb</p>

sj/app/views/white_list/new.html.erb
<h1>WhiteList#new</h1>
<p>Find me in app/views/white_list/new.html.erb</p>